<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.17763.0</TargetFramework>

    <EnableWindowsTargeting>true</EnableWindowsTargeting>
	  <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	
    <PackageId>FastKeySimulator</PackageId>
    <Title>FastKeySimulator</Title>
    <Version>1.2.3</Version>
    <Authors>Turba</Authors>

    <Copyright>Apache-2.0 license</Copyright>

    <Description>
The FastKeySimulator library for C# allows programmatic control of the keyboard and mouse in Windows via the WinAPI.
It uses the low-level SendInput API, which emulates physical key presses, mouse clicks, and cursor movements.
    </Description>

    <PackageProjectUrl>https://github.com/nazar650/FastKeySimulator-Library</PackageProjectUrl>

    <PackageIcon>FastKey.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/nazar650/FastKeySimulator-Library</RepositoryUrl>

    <PackageTags>keyboard,sendinput,winapi,key-simulator,automation</PackageTags>

	  <PackageLicenseExpression>MIT</PackageLicenseExpression>   

    <ApplicationIcon>FastKey.ico</ApplicationIcon>

    <SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>

  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>1701;1702;CA1416</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>1701;1702;CA1416</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="FastKey.ico" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\..\..\..\Загрузки\FastKey.png" Pack="true" PackagePath="\" />
    <None Include="..\..\..\..\..\Загрузки\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
